# -*- coding: utf-8 -*-
"""Survival Analysis - HR, OD, RR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ax7I9-k29uIWF8Z1nxeoTf4WACkk58jr

# Survival Analysis - HR, OD, RR

## a)

**For given data determine the variable anemia. Assume that women (0) are anemic if their hemoglobin < 12, and men (1) if their hemoglobin < 13. Then determine the HR, RR and OR statistics and interpret the results.**
"""

dane = read.table("http://theta.edu.pl/wp-content/uploads/2021/10/Dane.csv", header = TRUE, sep=';',dec = '.')
head(dane)

#Selecting the 3rd and 7th columns
head(dane[, c(3,7)])

dim(dane)

summary(dane)

hist(dane$Hemoglobina)

dane$anemia <- 0 # Assigning an initial value of 0 for all individuals in the new column "anemia"
dane[dane[, 3] == 0, 7] # Hemoglobin values for womens

dane[dane[,3] == 1,7]# Hemoglobin values for mens

dane$anemia[dane$SEX == 0 & dane$Hemoglobin < 12] <- 1 # Encoding women with anemia
dane$anemia[dane$SEX == 1 & dane$Hemoglobin < 13] <- 1 # Encoding men with anemia

table(dane$anemia)

"""80 individuals without anemia and 7 with anemia"""

table(dane$SEX, dane$anemia)

""" 1 woman with anemia and 6 men with anemia, vertically represents gender, horizontally represents anemia."""

dane[dane$anemia == 1, c(3,7,9)]

Oa = 1; Ob = 6; p = 7/87; Ea = 17 * p; Eb = 70 * p

#Where:

#p represents the ratio of individuals with anemia to the total population.
#Oa represents the number of individuals with anemia in group A (women).
#Ob represents the number of individuals with anemia in group B (men).
#Ea represents the expected number of individuals with anemia in group A (women).
#Eb represents the expected number of individuals with anemia in group B (men).
#Using the given values:

#Oa = 1 (1 woman with anemia)
#Ob = 6 (6 men with anemia)
#p = 7/87 (ratio of 7 individuals with anemia out of the total population of 87)
#Ea = 17 * p (expected number of women with anemia)

"""Where:

* p represents the ratio of individuals with anemia to the total population.
* Oa represents the number of individuals with anemia in group A (women).
* Ob represents the number of individuals with anemia in group B (men).
* Ea represents the expected number of individuals with anemia in group A (women).
* Eb represents the expected number of individuals with anemia in group B (men).

Using the given values:

* Oa = 1 (1 woman with anemia)
* Ob = 6 (6 men with anemia)
* p = 7/87 (ratio of 7 individuals with anemia out of the total population of 87)
* Ea = 17 * p (expected number of women with anemia)
"""

#Hazard ratio (HR)
HR = (Ob / Eb) / (Oa / Ea)
HR

"""The hazard ratio (HR) is calculated as the ratio of the hazard (risk) of anemia in men compared to women. In this case, the HR is approximately 1.45.

Interpretation: The risk of anemia in men is 1.45 times higher than in women.
"""

#Relative Risk (RR)

RR = (6/70) / (1/17)
RR

"""RR is the ratio of the number of individuals with anemia to the total number of individuals in each group (men to women)

The relative risk (RR) is calculated as the ratio of the risk of anemia in men to the risk of anemia in women. In this case, the RR is approximately 1.45.

Interpretation: The risk of anemia in men is 1.45 times higher than in women.
"""

#Odds Ratio (OR)
OR = (6/64) / (1/16)
OR

"""Odds Ratio (OR)

The ratio of the number of individuals with anemia to the number of individuals without anemia in each group (men to women)

The odds ratio (OR) is calculated as the ratio of the odds of having anemia in men to the odds of having anemia in women. In this case, the OR is approximately 1.5.

Interpretation: The odds of having anemia in men are approximately 1.5 times higher than in women.

##  b)

**For the above data, determine the survival time of each patient, and then
determine the 3-year "follow-up" and KaplanMeier survival function estimator.**
"""

dane$FU = as.Date(dane$Stop) - as.Date(dane$Start)
dane$FU = as.integer(as.Date(dane$Stop) - as.Date(dane$Start))

#Creating data where a period longer than 3 years (1095 days) is represented as 1095
dane$FU2 <- dane$FU
dane$FU2[dane$FU > 1095] <- 1095

#Creating data where individuals with anemia detected after the 3rd year of the study are assigned a value of 0 (indicating no anemia)
dane$anemia2 <- dane$anemia
dane$anemia2[dane$FU > 1095 & dane$anemia == 1] <- 0

library(survival)

km = survfit(Surv(dane$FU2, dane$anemia2) ~ 1)
km

"""The results show that there were 87 individuals included in the analysis. Out of these, 6 events (such as deaths or other defined outcomes) were observed. However, the median survival time and the 95% confidence interval for the survival estimates are not provided in the output (NA represents missing values). Therefore, further interpretation of the survival estimates cannot be made based on this specific output."""

summary(km)

plot(km, col="blue", lwd = 2)
plot(km, col="blue", lwd = 2, conf.int = FALSE) #without confidence interval

"""The absence of a median means that it is not possible to determine the exact value of the median survival time based on the available data. This can be due to various reasons such as insufficient follow-up time, no events (e.g., deaths) occurring, or a small sample size in the study. In such cases, it is difficult to ascertain the central value of survival time for the analyzed group.

## c)

**For previous data, determine the median survival and its 95% confidence interval, and
determine the hazard function for the first and third years.**
"""

#it is impossible to determine the median, because less than half of the people became ill

km

summary(km)

H1 = 0/ (365 * 87)
H1 # hazard ratio for day
H1 * 365 # hazard ratio for year

"""No individuals with anemia were detected in the first year """

dane2 = dane[, c(11, 12)]
dane2$FU2 =dane$FU2 - 730

colSums(dane2)

sum(dane2$FU2)

"""So much time survived people (with anemia, healthy and censored)"""

sum(dane2$anemia2)

"""The number of people with anemia"""

H3 = sum(dane2$anemia2) / sum(dane2$FU2) # hazard ratio for day
H3 # hazard ratio for day
H3 * 365 # hazard ratio for year

"""Given these hazard ratio values, it suggests that the risk of the event occurring in the group associated with the higher hazard ratio is significantly lower compared to the group associated with the lower hazard ratio."""

